In [109]:
import plotly.express as px 
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

df = pd.read_csv('cleaned_data.csv')

In [136]:
print(df.head())

   year    state    demographic   comparing_focus_group  \
0  2011  Alabama  Mental Health  Severe Mental Distress
1  2011  Alabama  Mental Health  Severe Mental Distress
2  2011  Alabama  Mental Health    Mild Mental Distress
3  2011  Alabama  Mental Health    Mild Mental Distress
4  2011  Alabama  Mental Health      No Mental Distress

       to_reference_group  focus_prevalence_num  reference_prevalence_num  \
0    Mild Mental Distress                  42.5                      26.0
1      No Mental Distress                  42.5                      18.9
2  Severe Mental Distress                  26.0                      42.5
3      No Mental Distress                  26.0                      18.9
4  Severe Mental Distress                  18.9                      42.5

   disparity_value_num
0                  1.6
1                  2.2
2                  0.6
3                  1.4
4                  0.4

In [4]:
print(df.comparing_focus_group.unique())

['Severe Mental Distress' 'Mild Mental Distress' 'No Mental Distress'
 'Homemaker/Student' 'Employed/Self' 'Retired' 'Unable to work'
 'Unemployed' '18-24' '25-44' '45-64' '65+' '<20000' '20000-74999'
 '>=75000' 'White' 'Black' 'Hispanic' 'AIAN' 'Asian']

In [5]:
print(df.year.unique())

[2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023]

In [120]:
df_filter = df[(df['demographic'] == 'Mental Health') 
               & (df['comparing_focus_group'] == 'Severe Mental Distress') 
                & (df['to_reference_group'] == 'No Mental Distress')]

In [121]:
df_filter.head()

,year,state,demographic,comparing_focus_group,to_reference_group,focus_prevalence_num,reference_prevalence_num,disparity_value_num
1,2011,Alabama,Mental Health,Severe Mental Distress,No Mental Distress,42.5,18.9,2.2
7,2011,Alaska,Mental Health,Severe Mental Distress,No Mental Distress,34.0,19.6,1.7
13,2011,Arizona,Mental Health,Severe Mental Distress,No Mental Distress,34.0,15.4,2.2
19,2011,Arkansas,Mental Health,Severe Mental Distress,No Mental Distress,47.7,19.2,2.5
25,2011,California,Mental Health,Severe Mental Distress,No Mental Distress,25.6,11.0,2.3

In [131]:
final_df = df_filter[['year','state', 'disparity_value_num']]

In [ ]:
state_to_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

final_df['state_code'] = final_df['state'].map(state_to_abbrev)

In [133]:
final_df.head()

    year       state  disparity_value_num state_code
1   2011     Alabama                  2.2         AL
7   2011      Alaska                  1.7         AK
13  2011     Arizona                  2.2         AZ
19  2011    Arkansas                  2.5         AR
25  2011  California                  2.3         CA

In [137]:
fig = px.choropleth(data_frame=final_df, locations='state_code', locationmode='USA-states', 
                    color='disparity_value_num', scope='usa', color_continuous_scale='Reds', animation_frame='year', animation_group='state_code',
                    labels={'disparity_value_num': 'Smoking Disparity Between Severe Distress and No Distress'}, 
                    title='Smoke Disparities of Heavy Stress Vs No Stress Levels From 2011-2023') 

fig.show()

Summary: This choropleth shows the smoking disparity between 'High Distress' and 'No Distress' mental groups accross all states from 2011-2023. The year slider allows one to compare the disparity rates between years. We see large disparities between the years of 2013-2015 with a slight drop off after that. This then reaches the largest disparity spread in the country in 2019 with a huge drop off in disparity during COVID/quarentine in 2020. One could begin to therorize if the time off from work during quarentine could have led to the disparity between these two groups decreasing significantly.

Histogram to show the general spread of all disparities across every demographic

In [139]:
max_dis = df['disparity_value_num'].max()
print(max_dis) 
min_dis = df['disparity_value_num'].min() 
print(min_dis)

11.6
0.1

In [172]:

prev_df = df[['year', 'focus_prevalence_num']]

In [173]:
fig2 = px.histogram(data_frame=prev_df, x='focus_prevalence_num', facet_col='year', 
                    nbins=20, labels={'focus_prevalence_num': 'Smoker %'}, facet_col_wrap=7,
                    facet_col_spacing=.03, facet_row_spacing=.05,
                    title='Percentage of all Smokers by Year') 
fig2.update_layout(bargap=.05)
fig2.update_xaxes(tickangle=45) 
fig2.show()

Summary: These graphs show the distribution of the percentages of smokers across all demographics from 2011-2023. On average we can see that 15-19.9% of all demographics were smokers. The percentage bins larger than 15-19.9% seem to be significantly lower. We begin to see change in the percentages from 2021-2023 where we see a large increase in the percentages of 5-14.99%, and a decrease in the 15-19.9%. This would mean that within the past few years we have seen an overall descrease in the amount of smokers accross all of the focus groups.